# Generated by Django 4.0.6 on 2022-10-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default=None, max_length=50, verbose_name='Modelo')),
                ('marca', models.CharField(default=None, max_length=50, verbose_name='Marca')),
                ('ano', models.CharField(default=None, max_length=9, verbose_name='Ano')),
                ('cor', models.CharField(default=None, max_length=50, verbose_name='Cor')),
                ('quilometragem', models.CharField(default=None, max_length=50, verbose_name='Quilometragem')),
                ('motorizacao', models.CharField(default=None, max_length=50, verbose_name='Motorização')),
                ('cambio', models.CharField(default=None, max_length=50, verbose_name='Câmbio')),
                ('preco', models.CharField(default=None, max_length=50, verbose_name='Preço')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('imagem_capa', models.ImageField(default=None, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 1 (Capa)')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_shop', models.CharField(default='About', max_length=50, verbose_name='Página')),
                ('titulo_shop', models.CharField(default=None, max_length=50, verbose_name='Título')),
                ('imagem_shop', models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_background', verbose_name='Background')),
                ('publicado_shop', models.BooleanField(default=False, verbose_name='Publicado')),
            ],
        ),
    ]
