# Generated by Django 4.0.6 on 2022-10-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default=None, max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(default=None, max_length=50, verbose_name='Marca')),
                ('ano', models.CharField(default=None, max_length=9, verbose_name='Ano')),
                ('cor', models.CharField(default=None, max_length=50, verbose_name='Cor')),
                ('quilometragem', models.CharField(default=None, max_length=50, verbose_name='Quilometragem')),
                ('motorizacao', models.CharField(default=None, max_length=50, verbose_name='Motorização')),
                ('cambio', models.CharField(default=None, max_length=50, verbose_name='Câmbio')),
                ('preco', models.CharField(default=None, max_length=50, verbose_name='Preço')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('imagem_1', models.ImageField(default=None, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 1 (Capa)')),
                ('imagem_2', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 2')),
                ('imagem_3', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 3')),
                ('imagem_4', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 4')),
                ('imagem_5', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 5')),
                ('imagem_6', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 6')),
                ('imagem_7', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 7')),
                ('imagem_8', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 8')),
                ('imagem_9', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 9')),
                ('imagem_10', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 10')),
                ('imagem_11', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 11')),
                ('imagem_12', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 12')),
                ('imagem_13', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 13')),
                ('imagem_14', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 14')),
                ('imagem_15', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 15')),
                ('imagem_16', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 16')),
                ('imagem_17', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 17')),
                ('imagem_18', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 18')),
                ('imagem_19', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 19')),
                ('imagem_20', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 20')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_shop', models.CharField(default='About', max_length=50, verbose_name='Página')),
                ('titulo_shop', models.CharField(default=None, max_length=50, verbose_name='Título')),
                ('imagem_shop', models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_background', verbose_name='Background')),
                ('publicado_shop', models.BooleanField(default=False, verbose_name='Publicado')),
            ],
        ),
    ]
