# Generated by Django 4.0.6 on 2022-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='modelo',
            field=models.CharField(default=None, max_length=100, verbose_name='Modelo'),
        ),
    ]
