# Generated by Django 4.0.6 on 2022-10-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='imagem_cinco',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 4'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_dez',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 10'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_dois',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 2'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_nove',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 9'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_oito',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 8'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_quatro',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 4'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_seis',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 6'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_sete',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 7'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_tres',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 3'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_um',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 1 (Capa)'),
        ),
    ]
