# Generated by Django 4.0.6 on 2022-10-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='imagem_10',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 10'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_11',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 11'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_12',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 12'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_13',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 13'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_14',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 14'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_15',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 15'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_16',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 16'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_17',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 17'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_18',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 18'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_19',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 19'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_2',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 2'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_20',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 20'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_3',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 3'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_4',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 4'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_5',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 5'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_6',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 6'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_7',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 7'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_8',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 8'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imagem_9',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem 9'),
        ),
    ]
