# Generated by Django 4.0.6 on 2022-11-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='preco',
            field=models.CharField(default='0', max_length=50, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='car',
            name='quilometragem',
            field=models.CharField(max_length=50, verbose_name='Quilometragem'),
        ),
    ]
