# Generated by Django 4.0.6 on 2022-10-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='imagem_shop',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_background', verbose_name='Background'),
        ),
    ]
