# Generated by Django 4.0.6 on 2022-10-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_car_imagem_10_alter_car_imagem_11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='opcionais',
            field=models.TextField(blank=True, null=True, verbose_name='Opcionais'),
        ),
    ]
