# Generated by Django 4.0.6 on 2022-10-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_car_imagem_10_alter_car_imagem_11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='imagem_shop',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_shop/imagens_background', verbose_name='Background (1920x400)'),
        ),
    ]
