# Generated by Django 4.0.6 on 2022-10-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_car_imagem_cinco_alter_car_imagem_dez_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='imagem_um',
            field=models.ImageField(default=None, upload_to='imagens_shop/imagens_carros/imagens_carro', verbose_name='Imagem 1 (Capa)'),
        ),
    ]
