# Generated by Django 4.0.6 on 2022-10-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_car_opcionais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Presonalização da página Home', 'verbose_name_plural': 'Presonalização da página Home'},
        ),
    ]
