# Generated by Django 4.0.6 on 2022-10-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ano',
            field=models.CharField(default=None, max_length=9, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='car',
            name='cambio',
            field=models.CharField(default=None, max_length=50, verbose_name='Câmbio'),
        ),
        migrations.AddField(
            model_name='car',
            name='cor',
            field=models.CharField(default=None, max_length=50, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='car',
            name='motorizacao',
            field=models.CharField(default=None, max_length=50, verbose_name='Motorização'),
        ),
        migrations.AddField(
            model_name='car',
            name='preco',
            field=models.CharField(default=None, max_length=50, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='car',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='car',
            name='quilometragem',
            field=models.CharField(default=None, max_length=50, verbose_name='Quilometragem'),
        ),
        migrations.AlterField(
            model_name='car',
            name='modelo',
            field=models.CharField(default=None, max_length=50, verbose_name='Modelo'),
        ),
    ]
