# Generated by Django 4.0.6 on 2022-10-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('shop', '0003_alter_shop_imagem_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.categoria', verbose_name='Categoria'),
        ),
    ]
