# Generated by Django 4.0.6 on 2022-10-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_car_options_alter_shop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Presonalização da página Estoque', 'verbose_name_plural': 'Presonalização da página Estoque'},
        ),
    ]
