# Generated by Django 4.0.6 on 2022-10-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_car_marca_alter_car_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='preco',
            field=models.CharField(default=None, max_length=50, verbose_name='Preço'),
        ),
    ]
