# Generated by Django 4.0.6 on 2022-10-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shop_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='imagem_shop',
            field=models.ImageField(default=None, upload_to='imagens_shop/imagens_background', verbose_name='Background (1920x400)'),
        ),
    ]
