# Generated by Django 4.0.6 on 2022-10-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_shop_imagem_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='quilometragem',
            field=models.FloatField(default=None, verbose_name='Quilometragem'),
        ),
    ]
