# Generated by Django 4.0.6 on 2022-10-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_car_quilometragem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='preco',
            field=models.FloatField(default=None, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='car',
            name='quilometragem',
            field=models.IntegerField(default=None, verbose_name='Quilometragem'),
        ),
    ]
