# Generated by Django 4.0.6 on 2022-10-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem_categoria',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_categorias', verbose_name='Imagem do quadrado na Home (400x250)'),
        ),
    ]
