# Generated by Django 4.1.2 on 2022-10-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_about', models.CharField(default='About', max_length=50, verbose_name='Página')),
                ('titulo_about', models.CharField(default=None, max_length=50, verbose_name='Título')),
                ('subtitulo_about', models.TextField(blank=True, default=None, max_length=50, null=True, verbose_name='Subtítulo')),
                ('descricao_about', models.TextField(default=None, max_length=500, null=True, verbose_name='Descrição')),
                ('publicado_about', models.BooleanField(default=False, verbose_name='Publicado')),
                ('imagem_about', models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_background', verbose_name='Background')),
                ('imagem_quadrado_um', models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texto_um', verbose_name='Imagem do texto 1')),
                ('imagem_quadrado_dois', models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texto_dois', verbose_name='Imagem do texto 2')),
                ('imagem_quadrado_tres', models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texte_tres', verbose_name='Imagem do texto 3')),
            ],
        ),
    ]
