# Generated by Django 4.0.6 on 2022-10-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='descricao_about',
        ),
        migrations.RemoveField(
            model_name='about',
            name='imagem_quadrado_dois',
        ),
        migrations.RemoveField(
            model_name='about',
            name='imagem_quadrado_tres',
        ),
        migrations.RemoveField(
            model_name='about',
            name='imagem_quadrado_um',
        ),
        migrations.RemoveField(
            model_name='about',
            name='subtitulo_about',
        ),
        migrations.AddField(
            model_name='about',
            name='imagem_texto_dois_about',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texto_dois', verbose_name='Imagem do quadrado 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='imagem_texto_tres_about',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texto_tres', verbose_name='Imagem do quadrado 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='imagem_texto_um_about',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texto_um', verbose_name='Imagem do quadrado 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='subtitulo_fotos_about',
            field=models.TextField(blank=True, default=None, max_length=50, null=True, verbose_name='Subtítulo das Fotos'),
        ),
        migrations.AddField(
            model_name='about',
            name='subtitulo_texto_about',
            field=models.TextField(blank=True, default=None, max_length=50, null=True, verbose_name='Subtítulo do texto'),
        ),
        migrations.AddField(
            model_name='about',
            name='texto_about',
            field=models.TextField(default=None, max_length=500, null=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='about',
            name='titulo_fotos_about',
            field=models.CharField(default=None, max_length=50, verbose_name='Título das Fotos'),
        ),
        migrations.AddField(
            model_name='about',
            name='titulo_texto_about',
            field=models.CharField(default=None, max_length=50, verbose_name='Título do texto'),
        ),
    ]
