# Generated by Django 4.0.6 on 2022-10-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'OIII5555', 'verbose_name_plural': 'OIII'},
        ),
    ]
