# Generated by Django 4.0.6 on 2022-10-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_descricao_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='texto_about',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_fotos_about',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título das Fotos'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_texto_about',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título do texto'),
        ),
    ]
