# Generated by Django 4.0.6 on 2022-10-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_texto_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='subtitulo_texto_about',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título do texto'),
        ),
    ]
