# Generated by Django 4.0.6 on 2022-10-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Presonalização da página Sobre Nós', 'verbose_name_plural': 'Presonalização da página Sobre Nós'},
        ),
    ]
