# Generated by Django 4.0.6 on 2022-10-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(default=' ', upload_to='imagens_about/imagens_funcionarios', verbose_name='Foto (400x442)'),
        ),
    ]
