# Generated by Django 4.0.6 on 2022-10-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_about_subtitulo_texto_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='imagem_about',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_background', verbose_name='Background (1920x400)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagem_texto_dois_about',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texto_dois', verbose_name='Imagem do quadrado 2 (400x500)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagem_texto_tres_about',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texto_tres', verbose_name='Imagem do quadrado 3 (400x500)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagem_texto_um_about',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texto_um', verbose_name='Imagem do quadrado 1 (400x500)'),
        ),
    ]
