# Generated by Django 4.0.6 on 2022-10-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_funcionario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='Cargo'),
        ),
    ]
