# Generated by Django 4.0.6 on 2022-10-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_about_imagem_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='texto_about',
            field=models.TextField(blank=True, default=None, max_length=100000, null=True, verbose_name='Texto'),
        ),
    ]
