# Generated by Django 4.0.6 on 2022-10-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_rename_link_facebook_funcionario_link_face_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='imagem_about',
            field=models.ImageField(default=' ', upload_to='imagens_about/imagens_background', verbose_name='Background (1920x400)'),
        ),
    ]
