# Generated by Django 4.0.6 on 2022-10-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_about_imagem_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='imagem_about',
            field=models.ImageField(upload_to='imagens_about/imagens_background', verbose_name='Background (1920x400)'),
        ),
    ]
