# Generated by Django 4.0.6 on 2022-10-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_about_imagem_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='imagem_texto_dois_about',
            field=models.ImageField(default=None, upload_to='imagens_about/imagens_texto_dois', verbose_name='Imagem do quadrado 2 (400x500)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagem_texto_tres_about',
            field=models.ImageField(default=None, upload_to='imagens_about/imagens_texto_tres', verbose_name='Imagem do quadrado 3 (400x500)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagem_texto_um_about',
            field=models.ImageField(default=None, upload_to='imagens_about/imagens_texto_um', verbose_name='Imagem do quadrado 1 (400x500)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitulo_fotos_about',
            field=models.TextField(default=None, max_length=50, verbose_name='Subtítulo das Fotos'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitulo_texto_about',
            field=models.CharField(default=None, max_length=50, verbose_name='Subtítulo do texto'),
        ),
        migrations.AlterField(
            model_name='about',
            name='texto_about',
            field=models.TextField(default=None, max_length=100000, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_fotos_about',
            field=models.CharField(default=None, max_length=50, verbose_name='Título das Fotos'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_texto_about',
            field=models.CharField(default=None, max_length=50, verbose_name='Título do texto'),
        ),
    ]
