# Generated by Django 4.1.3 on 2022-11-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_about_imagem_texto_dois_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='subtitulo_fotos_about',
            field=models.CharField(default=None, max_length=50, verbose_name='Subtítulo da Equipe de Funcionários'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_fotos_about',
            field=models.CharField(default=None, max_length=50, verbose_name='Título da Equipe de Funcionários'),
        ),
    ]
