# Generated by Django 4.0.6 on 2023-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDeConservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado_de_conservacao', models.CharField(max_length=50, verbose_name='Estado de Conservacao')),
                ('imagem_estado_de_conservacao', models.ImageField(blank=True, null=True, upload_to='estado_de_conservacao', verbose_name='Imagem do quadrado na Home (400x250)')),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='imagem_categoria',
        ),
    ]
