# Generated by Django 4.0.6 on 2023-01-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_estadodeconservacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadodeconservacao',
            name='imagem_estado_de_conservacao',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_estado_de_conservacao', verbose_name='Imagem do quadrado na Home (400x250)'),
        ),
    ]
