# Generated by Django 4.1.5 on 2023-01-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_home_titulo_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='descricao_home',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
