# Generated by Django 4.1.5 on 2023-01-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_home_descricao_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualidadesHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_qualidade', models.CharField(default='', max_length=50, verbose_name='Qualidade')),
                ('descricao_qualidade', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Descrição da qualidade')),
                ('icon_qualidade', models.ImageField(default=None, upload_to='imagens_home/icon_qualidades', verbose_name='Icon (75x75)')),
            ],
        ),
    ]
