# Generated by Django 4.1.5 on 2023-01-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_qualidadeshome'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualidadeshome',
            name='publicado_qualidade',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
