# Generated by Django 4.1.5 on 2023-01-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_qualidadeshome_publicado_qualidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualidadeshome',
            options={'verbose_name': 'Qualidade', 'verbose_name_plural': 'Qualidades'},
        ),
    ]
