# Generated by Django 4.1.5 on 2023-01-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_qualidadeshome_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='descricao_quadrado_grande_dois',
        ),
        migrations.RemoveField(
            model_name='home',
            name='descricao_quadrado_grande_tres',
        ),
        migrations.RemoveField(
            model_name='home',
            name='descricao_quadrado_grande_um',
        ),
        migrations.RemoveField(
            model_name='home',
            name='titulo_quadrado_grande_dois',
        ),
        migrations.RemoveField(
            model_name='home',
            name='titulo_quadrado_grande_tres',
        ),
        migrations.RemoveField(
            model_name='home',
            name='titulo_quadrado_grande_um',
        ),
    ]
