# Generated by Django 4.1.5 on 2023-01-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_home_descricao_quadrado_grande_dois_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualidadeshome',
            name='nome_qualidade',
            field=models.CharField(default='', max_length=15, verbose_name='Qualidade'),
        ),
    ]
