# Generated by Django 4.1.5 on 2023-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_qualidadeshome_nome_qualidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualidadeshome',
            name='descricao_qualidade',
            field=models.TextField(blank=True, default=None, max_length=60, null=True, verbose_name='Descrição da qualidade'),
        ),
    ]
