# Generated by Django 4.1.5 on 2023-01-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_qualidadeshome_descricao_qualidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualidadeshome',
            name='nome_qualidade',
            field=models.CharField(default='', max_length=20, verbose_name='Qualidade'),
        ),
    ]
