# Generated by Django 4.0.6 on 2023-01-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_alter_estadodeconservacao_imagem_estado_de_conservacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default=None, max_length=100, verbose_name='Modelo')),
                ('ano', models.CharField(default=None, max_length=9, verbose_name='Ano')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('motorizacao', models.CharField(default=None, max_length=20, verbose_name='Motorização')),
                ('preco', models.FloatField(default='0', verbose_name='Preço')),
                ('opcionais', models.TextField(blank=True, null=True, verbose_name='Opcionais')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('cambio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.cambio', verbose_name='Câmbio')),
                ('categoria_carro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.categoria', verbose_name='Categoria')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.cor', verbose_name='Cor')),
                ('estado_de_conservacao', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.estadodeconservacao', verbose_name='Estado de Conservacao')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_shop', models.CharField(default='About', max_length=50, verbose_name='Página')),
                ('titulo_shop', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Título')),
                ('imagem_shop', models.ImageField(blank=True, default=None, null=True, upload_to='imagens_shop/imagens_background', verbose_name='Background (1920x400)')),
                ('publicado_shop', models.BooleanField(default=False, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Presonalização da página Estoque',
                'verbose_name_plural': 'Presonalização da página Estoque',
            },
        ),
        migrations.CreateModel(
            name='ImagesCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(default=None, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.car')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
