# Generated by Django 4.1.5 on 2023-01-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='titulo_shop',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título'),
        ),
    ]
