# Generated by Django 4.1.5 on 2023-01-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_titulo_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='titulo_shop',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Título'),
        ),
    ]
