# Generated by Django 4.1.5 on 2023-01-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_titulo_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='motorizacao',
            field=models.CharField(default=None, max_length=20, verbose_name='Motorização'),
        ),
    ]
