# Generated by Django 4.0.6 on 2023-01-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_car_motorizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(default=None, upload_to='imagens_shop/imagens_carros', verbose_name='Imagem')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.car')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
