# Generated by Django 4.0.6 on 2023-01-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_imagescar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='imagem_10',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_11',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_12',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_13',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_14',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_15',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_16',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_17',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_18',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_19',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_20',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_5',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_6',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_7',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_8',
        ),
        migrations.RemoveField(
            model_name='car',
            name='imagem_9',
        ),
    ]
