# Generated by Django 4.0.6 on 2023-01-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_car_imagem_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
    ]
