# Generated by Django 4.0.6 on 2022-10-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_home', models.CharField(default='Home', max_length=50, verbose_name='Página')),
                ('titulo_home', models.CharField(default=None, max_length=50, verbose_name='Título')),
                ('subtitulo_home', models.TextField(blank=True, default=None, max_length=50, null=True, verbose_name='Subtítulo')),
                ('descricao_home', models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Descrição')),
                ('publicado_home', models.BooleanField(default=False, verbose_name='Publicado')),
                ('imagem_home', models.ImageField(default=None, upload_to='imagens_home/background_header', verbose_name='Background (1920x803)')),
                ('titulo_quadrado_grande_um', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título 1 do quadrado grande ')),
                ('descricao_quadrado_grande_um', models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Descrição 1 do quadrado grande ')),
                ('titulo_quadrado_grande_dois', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título 2 do quadrado grande')),
                ('descricao_quadrado_grande_dois', models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Descrição 2 do quadrado grande ')),
                ('titulo_quadrado_grande_tres', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título 3 do quadrado grande')),
                ('descricao_quadrado_grande_tres', models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Descrição 3 do quadrado grande ')),
                ('imagem_final_home', models.ImageField(blank=True, null=True, upload_to='imagens_home/background_footer', verbose_name='Imagem do final da página (1920x803)')),
                ('titulo_final_home', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título do final da página')),
                ('subtitulo_final_home', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Subtitulo do final da página')),
                ('conteudo_botao_home', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Conteudo do botão do final da página')),
                ('link_botao_home', models.CharField(blank=True, default=' ', max_length=1000, null=True, verbose_name='Link do botão do final da página')),
            ],
        ),
    ]
