# Generated by Django 4.1.2 on 2022-10-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_home', models.CharField(default='Home', max_length=50, verbose_name='Página')),
                ('titulo_home', models.CharField(default=None, max_length=50, verbose_name='Título')),
                ('subtitulo_home', models.TextField(blank=True, default=None, max_length=50, null=True, verbose_name='Subtítulo')),
                ('descricao_home', models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Descrição')),
                ('publicado_home', models.BooleanField(default=False, verbose_name='Publicado')),
                ('imagem_home', models.ImageField(blank=True, null=True, upload_to='imagens_home/', verbose_name='Background')),
                ('titulo_quadrado_um', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título do quadrado 1')),
                ('imagem_quadrado_um', models.ImageField(blank=True, null=True, upload_to='imagens_home/quadrado1', verbose_name='Imagem do quadrado 1')),
                ('titulo_quadrado_dois', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título do quadrado 2')),
                ('imagem_quadrado_dois', models.ImageField(blank=True, null=True, upload_to='imagens_home/quadrado2', verbose_name='Imagem do quadrado 2')),
                ('titulo_quadrado_tres', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título do quadrado 3')),
                ('imagem_quadrado_tres', models.ImageField(blank=True, null=True, upload_to='imagens_home/quadrado3', verbose_name='Imagem do quadrado 3')),
            ],
        ),
    ]
