# Generated by Django 4.0.6 on 2022-10-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='subtitulo_home',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Subtítulo'),
        ),
    ]
