# Generated by Django 4.1.2 on 2022-10-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_imagem_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='imagem_home',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_home/background', verbose_name='Background (1920x803)'),
        ),
    ]
