# Generated by Django 4.0.6 on 2022-10-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_subtitulo_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='conteudo_botao_home',
        ),
        migrations.RemoveField(
            model_name='home',
            name='imagem_final_home',
        ),
        migrations.RemoveField(
            model_name='home',
            name='link_botao_home',
        ),
        migrations.RemoveField(
            model_name='home',
            name='subtitulo_final_home',
        ),
        migrations.RemoveField(
            model_name='home',
            name='titulo_final_home',
        ),
    ]
