# Generated by Django 4.0.6 on 2022-10-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_home_conteudo_botao_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_grande_dois',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Descrição 2 do quadrado grande '),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_grande_tres',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Descrição 3 do quadrado grande '),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_grande_um',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Descrição 1 do quadrado grande '),
        ),
    ]
