# Generated by Django 4.0.6 on 2022-10-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_home_descricao_quadrado_grande_dois_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Presonalização da página Home', 'verbose_name_plural': 'Presonalização da página Home'},
        ),
    ]
