# Generated by Django 4.1.2 on 2022-10-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_home_imagem_quadrado_dois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='imagem_final_home',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_home/background', verbose_name='Imagem do final da página'),
        ),
        migrations.AddField(
            model_name='home',
            name='subtitulo_final_home',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Subtitulo do final da página'),
        ),
        migrations.AddField(
            model_name='home',
            name='titulo_final_home',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título do final da página'),
        ),
    ]
