# Generated by Django 4.1.2 on 2022-10-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_home_imagem_final_home_home_subtitulo_final_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='conteudo_botao_home',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Conteudo do botão do final da página'),
        ),
        migrations.AddField(
            model_name='home',
            name='link_botão_home',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True, verbose_name='Link do botão do final da página'),
        ),
        migrations.AlterField(
            model_name='home',
            name='imagem_final_home',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_home/background', verbose_name='Imagem do final da página (1920x208)'),
        ),
    ]
