# Generated by Django 4.0.6 on 2022-11-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_home_titulo_quadrado_grande_dois_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='imagem_home',
            field=models.ImageField(default=None, upload_to='imagens_home/background', verbose_name='Background (1920x803)'),
        ),
    ]
