# Generated by Django 4.1.2 on 2022-10-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_home_conteudo_botao_home_home_link_botão_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='link_botão_home',
        ),
        migrations.AddField(
            model_name='home',
            name='link_botao_home',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True, verbose_name='Link do botão do final da página'),
        ),
    ]
