# Generated by Django 4.1.2 on 2022-10-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_home_link_botão_home_home_link_botao_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='imagem_home',
            field=models.ImageField(default=None, upload_to='imagens_home/background', verbose_name='Background (1920x803)'),
        ),
    ]
