# Generated by Django 4.1.2 on 2022-10-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_home_imagem_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='descricao_quadrado_grande_um',
            field=models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Descrição 1 do quadrado grande '),
        ),
        migrations.AddField(
            model_name='home',
            name='titulo_quadrado_grande_dois',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título 2 do quadrado grande'),
        ),
        migrations.AddField(
            model_name='home',
            name='titulo_quadrado_grande_tres',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título 3 do quadrado grande'),
        ),
        migrations.AddField(
            model_name='home',
            name='titulo_quadrado_grande_um',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título 1 do quadrado grande '),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_home',
            field=models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Descrição'),
        ),
    ]
