# Generated by Django 4.1.3 on 2022-11-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_home_imagem_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='titulo_home',
            field=models.CharField(default=None, max_length=7, verbose_name='Título'),
        ),
    ]
