# Generated by Django 4.1.3 on 2022-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_home_titulo_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='descricao_home',
            field=models.TextField(blank=True, default=None, max_length=35, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='home',
            name='subtitulo_home',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Subtítulo'),
        ),
    ]
