# Generated by Django 4.1.2 on 2022-10-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_home_descricao_quadrado_grande_um_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='descricao_quadrado_grande_dois',
            field=models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Descrição 2 do quadrado grande '),
        ),
        migrations.AddField(
            model_name='home',
            name='descricao_quadrado_grande_tres',
            field=models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Descrição 3 do quadrado grande '),
        ),
    ]
