# Generated by Django 4.0.6 on 2022-10-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_home_descricao_quadrado_grande_dois_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='imagem_final_home',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_home/background', verbose_name='Imagem do final da página'),
        ),
        migrations.AlterField(
            model_name='home',
            name='imagem_home',
            field=models.ImageField(default=None, upload_to='imagens_home/background', verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='home',
            name='imagem_quadrado_dois',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_home/quadrado2', verbose_name='Imagem do quadrado 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='imagem_quadrado_tres',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_home/quadrado3', verbose_name='Imagem do quadrado 3'),
        ),
        migrations.AlterField(
            model_name='home',
            name='imagem_quadrado_um',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_home/quadrado1', verbose_name='Imagem do quadrado 1'),
        ),
    ]
