# Generated by Django 4.0.6 on 2022-10-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_home_imagem_final_home_alter_home_imagem_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='imagem_final_home',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_home/background/footer', verbose_name='Imagem do final da página'),
        ),
        migrations.AlterField(
            model_name='home',
            name='imagem_home',
            field=models.ImageField(default=None, upload_to='imagens_home/background/header', verbose_name='Background'),
        ),
    ]
