# Generated by Django 4.0.6 on 2022-10-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_home_imagem_final_home_alter_home_imagem_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='imagem_quadrado_dois',
        ),
        migrations.RemoveField(
            model_name='home',
            name='imagem_quadrado_tres',
        ),
        migrations.RemoveField(
            model_name='home',
            name='imagem_quadrado_um',
        ),
        migrations.RemoveField(
            model_name='home',
            name='titulo_quadrado_dois',
        ),
        migrations.RemoveField(
            model_name='home',
            name='titulo_quadrado_tres',
        ),
        migrations.RemoveField(
            model_name='home',
            name='titulo_quadrado_um',
        ),
    ]
