# Generated by Django 4.0.6 on 2022-10-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_home_imagem_quadrado_dois_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='imagem_final_home',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_home/background_footer', verbose_name='Imagem do final da página (1920x803)'),
        ),
        migrations.AlterField(
            model_name='home',
            name='imagem_home',
            field=models.ImageField(default=None, upload_to='imagens_home/background_header', verbose_name='Background (1920x803)'),
        ),
    ]
