# Generated by Django 4.1.5 on 2023-01-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_subtitulo_fotos_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='imagem_texto_dois_about',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='imagens_about/imagens_texto_dois', verbose_name='Imagem do quadrado 2 (400x500)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagem_texto_tres_about',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='imagens_about/imagens_texto_tres', verbose_name='Imagem do quadrado 3 (400x500)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagem_texto_um_about',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='imagens_about/imagens_texto_um', verbose_name='Imagem do quadrado 1 (400x500)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitulo_texto_about',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Subtítulo do texto'),
        ),
        migrations.AlterField(
            model_name='about',
            name='texto_about',
            field=models.TextField(blank=True, default=None, max_length=100000, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_about',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_texto_about',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título do texto'),
        ),
    ]
